language: node_js
node_js:
  - 'stable'
cache:
  directories:
    - 'node_modules'
before_script:
  - npm install
  - psql -c 'create database travis_ci_test;' -U postgres
script:
  - npm test
after_success:
  - npm run coverage
  - npm run coveralls
